version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - MONGO_URL=mongodb+srv://admin:bimskuy25@inventaris.mifkcjy.mongodb.net/Inventory?retryWrites=true&w=majority
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
